# Harmony mainnet node
version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 20m
      max-file: "3"

services:
  moonbeam:
    image: purestake/moonbeam:${DOCKER_TAG}
    #image: moonbeam:local
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    #  args:
    #    - DOCKER_TAG=${DOCKER_TAG}
    restart: unless-stopped
    volumes:
      - moonbeam-data:/data
      - ./runtimes:/runtimes
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: moonbeam
    ports:
      - 30333:30333/tcp
      - 30334:30334/tcp
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    <<: *logging
    entrypoint:
      - /moonbeam/moonbeam
      - --base-path
      - /data
      - --chain
      - ${CHAIN} 
      - --name
      - ${NODE_NAME}
      - --execution
      - wasm
      - --wasm-execution
      - compiled
      - --pruning
      - archive
      - --db-cache
      - ${DB_CACHE_SIZE}
      - --rpc-port
      - ${EC_RPC_PORT}
      - --rpc-external
      - --ws-port
      - ${EC_WS_PORT}
      - --ws-external
      - --rpc-cors
      - all
      - --public-addr
      - /ip4/${SERVER_IP}
      - --
      - --execution
      - wasm
      - --pruning
      - "1000"
      - --name
      - "${NODE_NAME} (Embedded Relay)"
      - --public-addr
      - /ip4/${SERVER_IP}
    labels:
      - traefik.enable=true
      - traefik.http.routers.moonbeam.service=moonbeam
      - traefik.http.routers.moonbeam.entrypoints=websecure
      - traefik.http.routers.moonbeam.rule=Host(`${EC_HOST}.${DOMAIN}`)
      - traefik.http.routers.moonbeam.tls.certresolver=letsencrypt
      - traefik.http.routers.moonbeamlb.service=moonbeam
      - traefik.http.routers.moonbeamlb.entrypoints=websecure
      - traefik.http.routers.moonbeamlb.rule=Host(`${EC_LB}.${DOMAIN}`)
      - traefik.http.routers.moonbeamlb.tls.certresolver=letsencrypt
      - traefik.http.services.moonbeam.loadbalancer.server.port=${EC_RPC_PORT}
      - traefik.http.routers.moonbeamws.service=moonbeamws
      - traefik.http.routers.moonbeamws.entrypoints=websecure
      - traefik.http.routers.moonbeamws.rule=Host(`${EC_WS_HOST}.${DOMAIN}`)
      - traefik.http.routers.moonbeamws.tls.certresolver=letsencrypt
      - traefik.http.routers.moonbeamwslb.service=moonbeamws
      - traefik.http.routers.moonbeamwslb.entrypoints=websecure
      - traefik.http.routers.moonbeamwslb.rule=Host(`${EC_WS_LB}.${DOMAIN}`)
      - traefik.http.routers.moonbeamwslb.tls.certresolver=letsencrypt
      - traefik.http.services.moonbeamws.loadbalancer.server.port=${EC_WS_PORT}

volumes:
  moonbeam-data:
