# Harmony mainnet node
version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 20m
      max-file: "3"

services:
  moonbeam:
    image: purestake/moonbeam:${DOCKER_TAG}
    #image: moonbeam:local
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    #  args:
    #    - DOCKER_TAG=${DOCKER_TAG}
    restart: unless-stopped
    volumes:
      - moonbeam-data:/data
      - ./runtimes:/runtimes
      - /etc/localtime:/etc/localtime:ro
    user: moonbeam
    ports:
      - ${PARA_P2P_PORT}:${PARA_P2P_PORT}/tcp
      - ${RELAY_P2P_PORT}:${RELAY_P2P_PORT}/tcp
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    <<: *logging
    entrypoint:
      - /moonbeam/moonbeam
      - --base-path
      - /data
      - --database
      - auto
      - --chain
      - ${CHAIN} 
      - --name
      - ${NODE_NAME}
      - --execution
      - wasm
      - --wasm-execution
      - compiled
      - --pruning
      - archive
      - --sync
      - full
      - --db-cache
      - ${DB_CACHE_SIZE}
      - --ws-port
      - ${WS_PORT}
      - --ws-external
      - --rpc-cors
      - all
      - --public-addr
      - /ip4/${SERVER_IP}
      - --port
      - ${PARA_P2P_PORT}
      - --
      - --execution
      - wasm
      #- --pruning
      #- "1000"
      - --name
      - "${NODE_NAME} (Embedded Relay)"
      - --public-addr
      - /ip4/${SERVER_IP}
      - --port
      - ${RELAY_P2P_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST}.service=${RPC_HOST}
      - traefik.http.routers.${RPC_HOST}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST}.rule=Host(`${RPC_HOST}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST}lb.service=${RPC_HOST}
      - traefik.http.routers.${RPC_HOST}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST}lb.rule=Host(`${RPC_LB}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST}.loadbalancer.server.port=${WS_PORT}

volumes:
  moonbeam-data:
